/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "NativeTestModuleSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeTestModuleCxxSpecJSI_systemVersion(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeTestModuleCxxSpecJSI *>(&turboModule)->systemVersion(
    rt
  );
}

NativeTestModuleCxxSpecJSI::NativeTestModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("NativeTestModule", jsInvoker) {
  methodMap_["systemVersion"] = MethodMetadata {0, __hostFunction_NativeTestModuleCxxSpecJSI_systemVersion};
}


} // namespace facebook::react
